### ISSUE TITLE
数据收集时出现错误

### ISSUE THREAD

**Issue by raozhongyu** [Kin-Zhang/mmfn#1]
感谢大佬的工作，有两个小问题想请教一下大佬：
1、第一个在carla_birdeye_view 里面写到一个路径为/home/kin/birdview_v3_cache/ 这个路径是存在生成鸟瞰图的地址吗，需要怎么修改呢
2、我在收集数据的时候报了以下错误，想请教一下大佬有没有什么建议
Traceback (most recent call last):
  File "/home/rao/workspace/ssd/mmfn-main/leaderboard/leaderboard/scenarios/scenario_manager.py", line 152, in _tick_scenario
    ego_action = self._agent()
  File "/home/rao/workspace/ssd/mmfn-main/leaderboard/leaderboard/autoagents/agent_wrapper.py", line 75, in __call__
    return self._agent()
  File "/home/rao/workspace/ssd/mmfn-main/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 115, in __call__
    control = self.run_step(input_data, timestamp)
  File "/home/rao/workspace/ssd/mmfn-main/team_code/expert_agent/auto_pilot.py", line 137, in run_step
    self.save_map(input_data)
  File "/home/rao/workspace/ssd/mmfn-main/team_code/expert_agent/common/base_agent.py", line 171, in save_map
    build_rmap([tmp_dir], lib_path)
  File "/home/rao/workspace/ssd/mmfn-main/team_code/expert_agent/common/utils.py", line 347, in build_rmap
    if (tmp[0][-2:]!="ok"):
IndexError: list index out of range
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rao/workspace/ssd/mmfn-main/leaderboard/leaderboard/leaderboard_evaluator.py", line 344, in _load_and_run_scenario
    self.manager.run_scenario()
  File "/home/rao/workspace/ssd/mmfn-main/leaderboard/leaderboard/scenarios/scenario_manager.py", line 136, in run_scenario
    self._tick_scenario(timestamp)
  File "/home/rao/workspace/ssd/mmfn-main/leaderboard/leaderboard/scenarios/scenario_manager.py", line 159, in _tick_scenario
    raise AgentError(e)
leaderboard.autoagents.agent_wrapper.AgentError: list index out of range

**Comment by Kin-Zhang** [comment]
1. 啊 不好意思 我忘改了 稍等 我改一下 sorry
2. 应该是lib包 忘安装了？
```
./scripts/setup_lib.sh
```

**Comment by Kin-Zhang** [comment]
我新push了两次 你pull一下再试试
e04d289d3b33c918f07af5c93c54ca2e4bc2e54e

**Comment by raozhongyu** [comment]
好的，感谢博主
